"""initial tables

Revision ID: 8f52e6d13386
Revises: 
Create Date: 2026-07-18 19:02:37.903696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8f52e6d13386'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors_same_as', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('authors_same_as_order_idx'))
        batch_op.drop_index(batch_op.f('authors_same_as_parent_id_idx'))

    op.drop_table('authors_same_as')
    with op.batch_alter_table('payload_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('payload_preferences_created_at_idx'))
        batch_op.drop_index(batch_op.f('payload_preferences_key_idx'))
        batch_op.drop_index(batch_op.f('payload_preferences_updated_at_idx'))

    op.drop_table('payload_preferences')
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('posts_author_idx'))
        batch_op.drop_index(batch_op.f('posts_category_idx'))
        batch_op.drop_index(batch_op.f('posts_created_at_idx'))
        batch_op.drop_index(batch_op.f('posts_featured_image_idx'))
        batch_op.drop_index(batch_op.f('posts_published_date_idx'))
        batch_op.drop_index(batch_op.f('posts_slug_idx'))
        batch_op.drop_index(batch_op.f('posts_status_idx'))
        batch_op.drop_index(batch_op.f('posts_updated_at_idx'))

    op.drop_table('posts')
    with op.batch_alter_table('payload_kv', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('payload_kv_key_idx'))

    op.drop_table('payload_kv')
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('media_created_at_idx'))
        batch_op.drop_index(batch_op.f('media_filename_idx'))
        batch_op.drop_index(batch_op.f('media_sizes_card_sizes_card_filename_idx'))
        batch_op.drop_index(batch_op.f('media_sizes_hero_sizes_hero_filename_idx'))
        batch_op.drop_index(batch_op.f('media_sizes_thumbnail_sizes_thumbnail_filename_idx'))
        batch_op.drop_index(batch_op.f('media_updated_at_idx'))

    op.drop_table('media')
    with op.batch_alter_table('posts_rels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('posts_rels_order_idx'))
        batch_op.drop_index(batch_op.f('posts_rels_parent_idx'))
        batch_op.drop_index(batch_op.f('posts_rels_path_idx'))
        batch_op.drop_index(batch_op.f('posts_rels_posts_id_idx'))

    op.drop_table('posts_rels')
    with op.batch_alter_table('posts_faqs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('posts_faqs_order_idx'))
        batch_op.drop_index(batch_op.f('posts_faqs_parent_id_idx'))

    op.drop_table('posts_faqs')
    with op.batch_alter_table('payload_locked_documents_rels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('payload_locked_documents_rels_authors_id_idx'))
        batch_op.drop_index(batch_op.f('payload_locked_documents_rels_categories_id_idx'))
        batch_op.drop_index(batch_op.f('payload_locked_documents_rels_media_id_idx'))
        batch_op.drop_index(batch_op.f('payload_locked_documents_rels_order_idx'))
        batch_op.drop_index(batch_op.f('payload_locked_documents_rels_parent_idx'))
        batch_op.drop_index(batch_op.f('payload_locked_documents_rels_path_idx'))
        batch_op.drop_index(batch_op.f('payload_locked_documents_rels_posts_id_idx'))
        batch_op.drop_index(batch_op.f('payload_locked_documents_rels_users_id_idx'))

    op.drop_table('payload_locked_documents_rels')
    with op.batch_alter_table('site_settings_same_as', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('site_settings_same_as_order_idx'))
        batch_op.drop_index(batch_op.f('site_settings_same_as_parent_id_idx'))

    op.drop_table('site_settings_same_as')
    with op.batch_alter_table('payload_locked_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('payload_locked_documents_created_at_idx'))
        batch_op.drop_index(batch_op.f('payload_locked_documents_global_slug_idx'))
        batch_op.drop_index(batch_op.f('payload_locked_documents_updated_at_idx'))

    op.drop_table('payload_locked_documents')
    with op.batch_alter_table('users_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('users_sessions_order_idx'))
        batch_op.drop_index(batch_op.f('users_sessions_parent_id_idx'))

    op.drop_table('users_sessions')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('categories_created_at_idx'))
        batch_op.drop_index(batch_op.f('categories_slug_idx'))
        batch_op.drop_index(batch_op.f('categories_updated_at_idx'))

    op.drop_table('categories')
    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('site_settings_logo_idx'))

    op.drop_table('site_settings')
    with op.batch_alter_table('payload_migrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('payload_migrations_created_at_idx'))
        batch_op.drop_index(batch_op.f('payload_migrations_updated_at_idx'))

    op.drop_table('payload_migrations')
    with op.batch_alter_table('image_blobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('image_blobs_media_id_idx'))

    op.drop_table('image_blobs')
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('authors_created_at_idx'))
        batch_op.drop_index(batch_op.f('authors_profile_image_idx'))
        batch_op.drop_index(batch_op.f('authors_slug_idx'))
        batch_op.drop_index(batch_op.f('authors_updated_at_idx'))

    op.drop_table('authors')
    with op.batch_alter_table('payload_preferences_rels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('payload_preferences_rels_order_idx'))
        batch_op.drop_index(batch_op.f('payload_preferences_rels_parent_idx'))
        batch_op.drop_index(batch_op.f('payload_preferences_rels_path_idx'))
        batch_op.drop_index(batch_op.f('payload_preferences_rels_users_id_idx'))

    op.drop_table('payload_preferences_rels')
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_cart_user_id'), ['user_id'], unique=False)
        batch_op.create_unique_constraint('uq_cart_user_product', ['user_id', 'product_id'])

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.alter_column('order_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.create_index('idx_order_items_order_id', ['order_id'], unique=False)
        batch_op.create_index('idx_order_items_product_id', ['product_id'], unique=False)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('total_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.create_index('idx_orders_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_orders_status', ['status'], unique=False)
        batch_op.create_index('idx_orders_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('stock',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_products_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_price'), ['price'], unique=False)

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('rating',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_index('idx_reviews_product_id', ['product_id'], unique=False)
        batch_op.create_index('idx_reviews_rating', ['rating'], unique=False)
        batch_op.create_index('idx_reviews_user_id', ['user_id'], unique=False)
        batch_op.create_unique_constraint('uq_review_user_product', ['user_id', 'product_id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('password', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('role', sa.String(), nullable=True))
        batch_op.drop_index(batch_op.f('users_created_at_idx'))
        batch_op.drop_index(batch_op.f('users_email_idx'))
        batch_op.drop_index(batch_op.f('users_updated_at_idx'))
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.drop_column('lock_until')
        batch_op.drop_column('hash')
        batch_op.drop_column('reset_password_token')
        batch_op.drop_column('reset_password_expiration')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('login_attempts')
        batch_op.drop_column('created_at')
        batch_op.drop_column('salt')

    with op.batch_alter_table('wishlist', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_wishlist_user_id'), ['user_id'], unique=False)
        batch_op.create_unique_constraint('uq_wishlist_user_product', ['user_id', 'product_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wishlist', schema=None) as batch_op:
        batch_op.drop_constraint('uq_wishlist_user_product', type_='unique')
        batch_op.drop_index(batch_op.f('ix_wishlist_user_id'))
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salt', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('now()'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('login_attempts', sa.NUMERIC(), server_default=sa.text('0'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('now()'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('reset_password_expiration', postgresql.TIMESTAMP(timezone=True, precision=3), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('reset_password_token', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('hash', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('lock_until', postgresql.TIMESTAMP(timezone=True, precision=3), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_index(batch_op.f('users_updated_at_idx'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('users_email_idx'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('users_created_at_idx'), ['created_at'], unique=False)
        batch_op.drop_column('role')
        batch_op.drop_column('password')
        batch_op.drop_column('name')

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint('uq_review_user_product', type_='unique')
        batch_op.drop_index('idx_reviews_user_id')
        batch_op.drop_index('idx_reviews_rating')
        batch_op.drop_index('idx_reviews_product_id')
        batch_op.alter_column('rating',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_price'))
        batch_op.drop_index(batch_op.f('ix_products_name'))
        batch_op.drop_index(batch_op.f('ix_products_category'))
        batch_op.alter_column('stock',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index('idx_orders_user_id')
        batch_op.drop_index('idx_orders_status')
        batch_op.drop_index('idx_orders_created_at')
        batch_op.alter_column('total_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_index('idx_order_items_product_id')
        batch_op.drop_index('idx_order_items_order_id')
        batch_op.alter_column('price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('order_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.drop_constraint('uq_cart_user_product', type_='unique')
        batch_op.drop_index(batch_op.f('ix_cart_user_id'))
        batch_op.alter_column('quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.create_table('payload_preferences_rels',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('users_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['payload_preferences.id'], name=op.f('payload_preferences_rels_parent_fk'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], name=op.f('payload_preferences_rels_users_fk'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('payload_preferences_rels_pkey'))
    )
    with op.batch_alter_table('payload_preferences_rels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('payload_preferences_rels_users_id_idx'), ['users_id'], unique=False)
        batch_op.create_index(batch_op.f('payload_preferences_rels_path_idx'), ['path'], unique=False)
        batch_op.create_index(batch_op.f('payload_preferences_rels_parent_idx'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('payload_preferences_rels_order_idx'), ['order'], unique=False)

    op.create_table('authors',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('profile_image_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('bio', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('job_title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['profile_image_id'], ['media.id'], name=op.f('authors_profile_image_id_media_id_fk'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('authors_pkey'))
    )
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('authors_updated_at_idx'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('authors_slug_idx'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('authors_profile_image_idx'), ['profile_image_id'], unique=False)
        batch_op.create_index(batch_op.f('authors_created_at_idx'), ['created_at'], unique=False)

    op.create_table('image_blobs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('media_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('blob_data', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('mime_type', sa.TEXT(), server_default=sa.text("'image/webp'::text"), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('image_blobs_pkey'))
    )
    with op.batch_alter_table('image_blobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('image_blobs_media_id_idx'), ['media_id'], unique=True)

    op.create_table('payload_migrations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('batch', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('payload_migrations_pkey'))
    )
    with op.batch_alter_table('payload_migrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('payload_migrations_updated_at_idx'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('payload_migrations_created_at_idx'), ['created_at'], unique=False)

    op.create_table('site_settings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('logo_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('domain', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('default_meta_title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('default_meta_description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('footer_text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('default_cta_heading', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('default_cta_description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('default_cta_button_text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('default_cta_button_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True, precision=3), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True, precision=3), autoincrement=False, nullable=True),
    sa.Column('schema_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['logo_id'], ['media.id'], name=op.f('site_settings_logo_id_media_id_fk'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('site_settings_pkey'))
    )
    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('site_settings_logo_idx'), ['logo_id'], unique=False)

    op.create_table('categories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('seo_title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('seo_description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cta_heading', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cta_description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cta_button_text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cta_button_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('categories_pkey'))
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('categories_updated_at_idx'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('categories_slug_idx'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('categories_created_at_idx'), ['created_at'], unique=False)

    op.create_table('users_sessions',
    sa.Column('_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('_parent_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True, precision=3), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True, precision=3), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['_parent_id'], ['users.id'], name=op.f('users_sessions_parent_id_fk'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('users_sessions_pkey'))
    )
    with op.batch_alter_table('users_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('users_sessions_parent_id_idx'), ['_parent_id'], unique=False)
        batch_op.create_index(batch_op.f('users_sessions_order_idx'), ['_order'], unique=False)

    op.create_table('payload_locked_documents',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('global_slug', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('payload_locked_documents_pkey'))
    )
    with op.batch_alter_table('payload_locked_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('payload_locked_documents_updated_at_idx'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('payload_locked_documents_global_slug_idx'), ['global_slug'], unique=False)
        batch_op.create_index(batch_op.f('payload_locked_documents_created_at_idx'), ['created_at'], unique=False)

    op.create_table('site_settings_same_as',
    sa.Column('_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('_parent_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['_parent_id'], ['site_settings.id'], name=op.f('site_settings_same_as_parent_id_fk'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('site_settings_same_as_pkey'))
    )
    with op.batch_alter_table('site_settings_same_as', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('site_settings_same_as_parent_id_idx'), ['_parent_id'], unique=False)
        batch_op.create_index(batch_op.f('site_settings_same_as_order_idx'), ['_order'], unique=False)

    op.create_table('payload_locked_documents_rels',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('users_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('media_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('posts_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('authors_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('categories_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['authors_id'], ['authors.id'], name=op.f('payload_locked_documents_rels_authors_fk'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['categories_id'], ['categories.id'], name=op.f('payload_locked_documents_rels_categories_fk'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], name=op.f('payload_locked_documents_rels_media_fk'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['payload_locked_documents.id'], name=op.f('payload_locked_documents_rels_parent_fk'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['posts_id'], ['posts.id'], name=op.f('payload_locked_documents_rels_posts_fk'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], name=op.f('payload_locked_documents_rels_users_fk'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('payload_locked_documents_rels_pkey'))
    )
    with op.batch_alter_table('payload_locked_documents_rels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('payload_locked_documents_rels_users_id_idx'), ['users_id'], unique=False)
        batch_op.create_index(batch_op.f('payload_locked_documents_rels_posts_id_idx'), ['posts_id'], unique=False)
        batch_op.create_index(batch_op.f('payload_locked_documents_rels_path_idx'), ['path'], unique=False)
        batch_op.create_index(batch_op.f('payload_locked_documents_rels_parent_idx'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('payload_locked_documents_rels_order_idx'), ['order'], unique=False)
        batch_op.create_index(batch_op.f('payload_locked_documents_rels_media_id_idx'), ['media_id'], unique=False)
        batch_op.create_index(batch_op.f('payload_locked_documents_rels_categories_id_idx'), ['categories_id'], unique=False)
        batch_op.create_index(batch_op.f('payload_locked_documents_rels_authors_id_idx'), ['authors_id'], unique=False)

    op.create_table('posts_faqs',
    sa.Column('_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('_parent_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('question', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('answer', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['_parent_id'], ['posts.id'], name=op.f('posts_faqs_parent_id_fk'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('posts_faqs_pkey'))
    )
    with op.batch_alter_table('posts_faqs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('posts_faqs_parent_id_idx'), ['_parent_id'], unique=False)
        batch_op.create_index(batch_op.f('posts_faqs_order_idx'), ['_order'], unique=False)

    op.create_table('posts_rels',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('posts_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['posts.id'], name=op.f('posts_rels_parent_fk'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['posts_id'], ['posts.id'], name=op.f('posts_rels_posts_fk'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('posts_rels_pkey'))
    )
    with op.batch_alter_table('posts_rels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('posts_rels_posts_id_idx'), ['posts_id'], unique=False)
        batch_op.create_index(batch_op.f('posts_rels_path_idx'), ['path'], unique=False)
        batch_op.create_index(batch_op.f('posts_rels_parent_idx'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('posts_rels_order_idx'), ['order'], unique=False)

    op.create_table('media',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('alt', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('thumbnail_u_r_l', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('mime_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('filesize', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('width', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('height', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('focal_x', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('focal_y', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('optimized_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('optimized_width', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('optimized_height', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('sizes_thumbnail_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sizes_thumbnail_width', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('sizes_thumbnail_height', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('sizes_thumbnail_mime_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sizes_thumbnail_filesize', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('sizes_thumbnail_filename', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sizes_card_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sizes_card_width', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('sizes_card_height', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('sizes_card_mime_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sizes_card_filesize', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('sizes_card_filename', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sizes_hero_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sizes_hero_width', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('sizes_hero_height', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('sizes_hero_mime_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sizes_hero_filesize', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('sizes_hero_filename', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('image_buffer', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('original_mime_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('_urlspatched', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('has_blob', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('media_pkey'))
    )
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('media_updated_at_idx'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('media_sizes_thumbnail_sizes_thumbnail_filename_idx'), ['sizes_thumbnail_filename'], unique=False)
        batch_op.create_index(batch_op.f('media_sizes_hero_sizes_hero_filename_idx'), ['sizes_hero_filename'], unique=False)
        batch_op.create_index(batch_op.f('media_sizes_card_sizes_card_filename_idx'), ['sizes_card_filename'], unique=False)
        batch_op.create_index(batch_op.f('media_filename_idx'), ['filename'], unique=True)
        batch_op.create_index(batch_op.f('media_created_at_idx'), ['created_at'], unique=False)

    op.create_table('payload_kv',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('payload_kv_pkey'))
    )
    with op.batch_alter_table('payload_kv', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('payload_kv_key_idx'), ['key'], unique=True)

    op.create_table('posts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reading_time', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('slug', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('draft', 'published', name='enum_posts_status'), server_default=sa.text("'draft'::enum_posts_status"), autoincrement=False, nullable=False),
    sa.Column('published_date', postgresql.TIMESTAMP(timezone=True, precision=3), autoincrement=False, nullable=True),
    sa.Column('modified_date', postgresql.TIMESTAMP(timezone=True, precision=3), autoincrement=False, nullable=True),
    sa.Column('featured_image_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('featured_image_alt', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('excerpt', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content_type', postgresql.ENUM('richText', 'markdown', name='enum_posts_content_type'), server_default=sa.text("'richText'::enum_posts_content_type"), autoincrement=False, nullable=False),
    sa.Column('rich_text_content', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('markdown_content', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('compiled_html', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cta_heading', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cta_description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cta_button_text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cta_button_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('meta_title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('meta_description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('focus_keyphrase', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('schema_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('toc', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], name=op.f('posts_author_id_authors_id_fk'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('posts_category_id_categories_id_fk'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['featured_image_id'], ['media.id'], name=op.f('posts_featured_image_id_media_id_fk'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('posts_pkey'))
    )
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('posts_updated_at_idx'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('posts_status_idx'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('posts_slug_idx'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('posts_published_date_idx'), ['published_date'], unique=False)
        batch_op.create_index(batch_op.f('posts_featured_image_idx'), ['featured_image_id'], unique=False)
        batch_op.create_index(batch_op.f('posts_created_at_idx'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('posts_category_idx'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('posts_author_idx'), ['author_id'], unique=False)

    op.create_table('payload_preferences',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('key', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('payload_preferences_pkey'))
    )
    with op.batch_alter_table('payload_preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('payload_preferences_updated_at_idx'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('payload_preferences_key_idx'), ['key'], unique=False)
        batch_op.create_index(batch_op.f('payload_preferences_created_at_idx'), ['created_at'], unique=False)

    op.create_table('authors_same_as',
    sa.Column('_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('_parent_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['_parent_id'], ['authors.id'], name=op.f('authors_same_as_parent_id_fk'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('authors_same_as_pkey'))
    )
    with op.batch_alter_table('authors_same_as', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('authors_same_as_parent_id_idx'), ['_parent_id'], unique=False)
        batch_op.create_index(batch_op.f('authors_same_as_order_idx'), ['_order'], unique=False)

    # ### end Alembic commands ###
